version: '3'

services:
#  mongo:
#    image: mongo
#    volumes: 
#      - mongo_data:/data/db
#    networks:
#      - proxy
#    logging:
#      driver: none
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#    labels:
#      - traefik.enable=false   
#  mongo-express:
#    image: mongo-express
#    networks:
#      - proxy
#    ports:
#      - 8081:8081
#    logging:
#      driver: none
#    depends_on:
#      - mongo
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#    labels:
#      traefik.backend: mongo
#      traefik.frontend.rule: Host:mongo.recursiveturtle.com
#      traefik.docker.network: proxy
#      traefik.port: 8081
  dev:
    image: node
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: npm run start
    networks:
      - proxy
    ports:
      - 3000:3000
      - 9229:9229
    labels:
      traefik.backend: dev
      traefik.frontend.rule: Host:dev.recursiveturtle.com
      traefik.docker.network: proxy
      traefik.port: 3000
      #traefik.port: 9229


volumes:
  mongo_data:

networks:
  proxy:
    external: true
